### ISSUE TITLE
Simplify go get instructions

### ISSUE THREAD

**Issue by myhndl** [polyswarm/perigord#3]
Use ellipsis:
```
$ go get -u https://github.com/swarmdotmarket/perigord/...
```

In installation instructions.

Blocks on moving templated .go files to a different file extension.

**Comment by mjkoo** [comment]
Fixed issue in 63cc9ca166d953be94f3ee85932ad4be1f37aa40 with templates, `go get` doesn't work out of the box still due to generated code. Don't particularly want to commit generated code to master, but that's apparently what the go tool wants. Will investigate solutions.

Dockerfile added to repo to simplify usage for docker users.
